### ISSUE TITLE
How to get usename from view?

### ISSUE THREAD

**Issue by montes2012** [SaschaDens/ldap-connector#19]
How to get usename from view?

{{ Auth::user()->username }} ?

Undefined property: Dsdevbe\LdapConnector\Model\User::$username

**Comment by SaschaDens** [comment]
{{ Auth::user()->getAuthIdentifier() will return you the current logged in username.
If you do {{ dd(Auth::user() }} you will see all the available properties.

Currently there are only limited available properties. More properties will be added in the future see issue: #17
