### ISSUE TITLE
publishing command not creating config/ldap.php

### ISSUE THREAD

**Issue by kayrules** [SaschaDens/ldap-connector#20]
Triggering command `php artisan vendor:publish ` not creating `config/ldap.php` file.

**Comment by SaschaDens** [comment]
Thanks for submitting an issue @kayrules 

I've updated the installation steps on the README. To solve your issue for the publishing you will need to add the following line in the providers array in `config/app.php`

`Dsdevbe\LdapConnector\LdapConnectorServiceProvider::class`

**Comment by kayrules** [comment]
Thank you @SaschaDens
