### ISSUE TITLE
Auth::attempt returning false

### ISSUE THREAD

**Issue by 11110101** [SaschaDens/ldap-connector#22]
Hello bro, excellent work doing this. I have implemented your solution but the next code returns false...

Auth::attempt(array('username' => "user", 'password' => "fancy password"))

I wrote some code in "authenticate" method from adLDAP.php file to see what was happening. That method returns true!! so the binding with my ldap server is done.

I have followed your tutorial completely but no answer :(, some suggestion? Do I have to add a model?

I'm using laravel 5 and playing with ldap with only php is working....

Kind regards!

**Comment by SaschaDens** [comment]
I've just tested with my LDAP server and it seems to be working.

Maybe there is something wrong in the configuration `config/ldap.php`. For example the `account_suffix`is correctly set?

When you perform an authenticate you don't add the `account_suffix`.
Example:
- user: testUser@test.com
- account_suffix = DC=test,DC=com

With this example you then can authenticate like this `Auth::attempt(array('username' => "test", 'password' => "fancy password"))` which return `true` if the authentication was successful.

Kind regards,
Sascha

**Comment by 11110101** [comment]
I got the solution, 
The issue was the way adldap is working when requesting information.

My LDAP implementation is too different according to business need, so it was throwing false when getting info.
So, I have changed some php files to get it in adldap library.
Thanks bro.

**Comment by SaschaDens** [comment]
Great! I'll close the issue. In case you experience  some other issues you always report them.
