### ISSUE TITLE
auth->guest() = 1

### ISSUE THREAD

**Issue by 11110101** [SaschaDens/ldap-connector#23]
Hello again bro, this is another question, maybe you can help me
I'm executing the next code.., I get the "Redirect" but when Authenticate handles the request is givingme that I'm a guest so returning to login according to my needs. I never get right user authenticated, always as guest.

//code in custom auth controller
if (Auth::attempt(array('username' => $username, 'password' => $password)))
{
    return Redirect::intended('dashboard');
}
//code in Authenticate.php
 public function handle($request, Closure $next)
    {
        if ($this->auth->guest()) // = 1

Kind regards!

**Comment by SaschaDens** [comment]
Hello @11110101,

It seems like the session is not stored when using `Auth::attempt`when using the `AuthController` provided by Laravel this issue is solved.

I'll mark this one as bug and i'll get back to this issue asap.

Kind regards,
Sascha

**Comment by SaschaDens** [comment]
The issue that I had was that my session was not stored which is not part of the Ldap-connector. However for me it was a dd() blocking my session persistance.

Could you check after you authenticate if you see your session on another route by using `dd(Session::all();` For your debugging help check the [Stackoverflow](http://stackoverflow.com/questions/30769434/laravel-5-session-not-persisting-after-user-is-logged-in) article which is related to session persistence.
