### ISSUE TITLE
ErrorException in LdapUserProvider.php line 61: Undefined index: username

### ISSUE THREAD

**Issue by ornerymoose** [SaschaDens/ldap-connector#24]
Hello, I've followed the instructions in the README closely and I'm running into an issue when adding 

protected $username = 'username';

to Http/Controllers/Auth/AuthController.php

'ErrorException in LdapUserProvider.php line 61: Undefined index: username' 

occurs when clicking 'Login' from my home page. 

I'm adding it right above the __construct function. Is there something I'm missing here?

PHP Version: 5.6.14
Laravel Framework version 5.0.33
Server version: Apache/2.4.6 (CentOS)
CentOS Linux release 7.1.1503 (Core) 
Derived from Red Hat Enterprise Linux 7.1 (Source)

This is a brand new Laravel application and I have not modified anything else. I would like to use the authentication that ships with Laravel. 

Let me know if I need to provide additional information.

**Comment by SaschaDens** [comment]
Hello @ornerymoose 

You need to add this to overwrite the default value for validation purpose. In the `AuthenticatesUsers` from Laravel on method `loginUsername` this contains the following line.

```php
return property_exists($this, 'username') ? $this->username : 'email';
```

By adding protected just above the `__construct` you override the field.

Now to solve your issue you need to be sure that your view(most likely `auth.login`) the form is acctually sending and input field `username`.

On laravel example [Authentication Quickstart](http://laravel.com/docs/5.1/authentication) ->Views this 
- `<input type="email" name="email" value="{{ old('email') }}">`

should be

- `<input type="text" name="username" value="{{ old('username') }}">`

Kind regards,
Sascha

**Comment by ornerymoose** [comment]
Ah, I see! Makes perfect sense, thank you for the very quick reply. :)
