### ISSUE TITLE
How to login with uid ?

### ISSUE THREAD

**Issue by wanlxp** [SaschaDens/ldap-connector#27]
I can login with uid now, How can i do it ?

**Comment by SaschaDens** [comment]
The ldap connector uses the user/pass to authenticate to the ldap.

Could you be a bit more specific please?

**Comment by wanlxp** [comment]
i want to auth with openldap, and auth with uid attribute, is this support ?

**Comment by SaschaDens** [comment]
I'll try to setup this weekend an openldap and come back with a solution asap.

**Comment by SaschaDens** [comment]
Have you succeeded to make any progress with openLdap UID auth? This should be possible.

I'll close this ticket for now but I'll reopen it in-case you still have some issues.

**Comment by juanlet** [comment]
could you provide an example of how to log in with uid using the auth.php?? I can't find any info on this
