### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by SaschaDens** [SaschaDens/ldap-connector#28]
Make package support new Laravel 5.2 version

**Comment by driverok** [comment]
hi. Please help.

i use "dsdevbe/ldap-connector": "dev-laravel-5-2-support"

here is my config  auth.php

'defaults'  => [
        'guard'     => 'web',
        'passwords' => 'users',
    ],
'guards'    => [
        'web' => [
            'driver'   => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver'   => 'token',
            'provider' => 'users',
        ],
    ],
'providers' => [
        'users' => [
            'driver' => 'ldap',
        ],
    ],
 'passwords' => [
        'users' => [
            'provider' => 'users',
            'email'    => 'auth.emails.password',
            'table'    => 'password_resets',
            'expire'   => 60,
        ],
    ],
];

i have ldap.php config

return [
    'plugins' => [
        'adldap' => [
            'account_suffix'     => '@domain.local',
            'domain_controllers' => [
                '192.168.0.1',
                'dc02.domain.local',
            ], // Load balancing domain controllers
            'base_dn'        => 'DC=domain,DC=local',
            'admin_username' => 'admin', // This is required for session persistance in the application
            'admin_password' => 'yourPassword',
        ],
    ],
];
 but when i connect to my site i have 
ErrorException in LdapConnectorServiceProvider.php line 28:
Please check if your configuration is available in config/auth.php 
 i make some debug and found  that method

 protected function hasLdapConfiguration($config)
    {
        return isset($config['adldap']) && is_array($config['adldap']);
    }
and i have wrong variable $config['driver']='ldap'

**Comment by SaschaDens** [comment]
Hello @driverok the `ldap.php`is not published anymore but is directly part of the configuration in `config/auth.php`.

You could find an example on the [Readme.md](https://github.com/SaschaDens/ldap-connector/tree/laravel-5-2-support#laravel-52---) of the branch at step 3.

Could you test this and let me know if you still have issues with the configuration?

Thanks in advance.

**Comment by driverok** [comment]
all fixed, thanx.
