### ISSUE TITLE
LdapConnectorServiceProvider Guard

### ISSUE THREAD

**Issue by edyrkaj** [SaschaDens/ldap-connector#29]
Hello,

Im using Laravel 5.2 and i got this error:
Class 'Dsdevbe\LdapConnector\Guard' not found.

Any idea ? Thnx

**Comment by SaschaDens** [comment]
The Authentication model is changed in Laravel 5.2 and that's also the reason that the current release doesn't work.

However to solve your issue you can make use of the other branch that I've created for the 5.2 support. use `composer require dsdevbe/ldap-connector:dev-laravel-5-2-support` and it will download the new source.

The issue for Laravel 5.2 support is still open #28

**Comment by edyrkaj** [comment]
Thank you
