### ISSUE TITLE
Laravel version 5.2.22 support

### ISSUE THREAD

**Issue by baaskoen** [SaschaDens/ldap-connector#30]
I'm getting the following error: FatalErrorException in LdapConnectorServiceProvider.php line 32:
Class 'Illuminate\Auth\Guard' not found.

Any ideas on how to fix this?

**Comment by WindSaber** [comment]
Are you working with the branch for 5.2 support? 
[https://github.com/SaschaDens/ldap-connector/tree/laravel-5-2-support](url)

**Comment by baaskoen** [comment]
Ah, my bad. Thanks, I will try that.
