### ISSUE TITLE
adldap/adldap no matching package found

### ISSUE THREAD

**Issue by jmdryden** [SaschaDens/ldap-connector#37]
Hi -- I'm on a Laravel 4.2 project and trying to install via Composer, version 1.2-dev:
$> composer require dsdevbe/dsdevbe 2.* 

I get:

"Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package dsdevbe/dsdevbe could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for dsdevbe/ldap-connector 2.* -> satisfiable by dsdevbe/ldap-connector[2.0.0].
    - dsdevbe/ldap-connector 2.0.0 requires adldap/adldap 4.0-stable -> no matching package found."

I know there is a adldap/adldap 4.0-stable. What am i missing?

**Comment by SaschaDens** [comment]
Hello @jmdryden 

I checked and it seems that adldap/adldap 4.0-stable is not available anymore on composer. (See [Packagist](https://packagist.org/packages/adldap/adldap#5.0.0.x-dev))

I will change this asap to an existing version [Adldap2](https://packagist.org/packages/adldap2/adldap2#v4.0.5) on the Laravel 4.2 branch.

**Comment by SaschaDens** [comment]
`composer require "dsdevbe/ldap-connector:dev-Laravel4.2"` would do the trick.
