### ISSUE TITLE
Suporte to Laravel 5.3

### ISSUE THREAD

**Issue by Leandro-b-03** [SaschaDens/ldap-connector#40]
Hi, how are you @SaschaDens, hope you re fine.

So man, I'm here to ask if the package will have Laravel 5.3 support I'm upgrading the core and your package is a vital one to my app.

Hope hear for you soon.

Thanks!

**Comment by qwertytech** [comment]
@Leandro-b-03 Just used this on my Laravel 5.3 project and had no compatibility issues.

**Comment by SaschaDens** [comment]
When I see the changelog of Laravel there is a few things changed regarding the authentication of Laravel.

I couldn't do my tests yet but as @qwertytech pointed out it seems to work.

**Comment by Leandro-b-03** [comment]
I don't know how to specify the ldap connection in auth.php, how I change the file without break it?

**Comment by qwertytech** [comment]
@SaschaDens I've tested it over the last 3 days and have had no issues with our 7,000 logins.

@Leandro-b-03 You just change the driver from whatever it is set as, to 'ldap'.

**Comment by Leandro-b-03** [comment]
@qwertytech Just found, thanks man.

So for who may has the same problem here below were must be change.

```
    'providers' => [
        'users' => [
            'driver' => 'eloquent', // <- here to ldap
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```
